default:
  before_script:
    - export PATH=$PATH:$GO_HOME/bin
    - go version
    - pwd

stages:
  - build
  - test
  
include:
  - local: 'unit_simple/.gitlab-ci.yml'
  - local: 'learning/.gitlab-ci.yml'

